# ----
# Site

title: Open Steno
url: https://opensteno.org
google_analytics_key: UA-102613911-1

permalink: pretty

# Values for the jekyll-seo-tag gem
logo: siteicon.png
description: Bringing stenography to everyone.
author:
  name: Plover
  email: plover@ploversteno.org
  twitter: plover

collections:
  events:
    sort-by: date

# -----
# Build

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

gems:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
